### ISSUE TITLE
Class traits not being gained upon using spellbooks

### ISSUE THREAD

**Issue by Meridian117** [RobbieNeko/Magical-Nights#9]
When I read up on various spells, it never gave me the "technomancer" or "kelvinist" class things, so I can't create the runes and therefore cannot create the class items.  It's both from scrolls and spellbooks.
Edit1:  I'm going to try updating the mod tomorrow and see if that helps, I'm also going to update to most current version of experimental and see if that fixes anything.

**Comment by RobbieNeko** [comment]
Yeah, I'd highly recommend updating to latest experimental first. (though I don't know if it'll properly give the traits to you upon learning a new spell even then, it'd be the kind of thing you'd ideally test with a class you haven't gotten a spell in yet).
If your game version is ~3 weeks old or older, there's a good chance you got caught in the period where it was borked because of a change I made to the c++ code in BN lol

**Comment by Meridian117** [comment]
Sounds good.  Are there debug options to delete spells?  If not then I will start a new character to test if it's working or not.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by RobbieNeko** [comment]
I don't *think* there's options to delete spells, no

**Comment by Meridian117** [comment]
Update fixed the issue for new character, but not old character.  I'm just going to debug in the traits and call it good.  Shouldn't be an issue moving forward

**Comment by RobbieNeko** [comment]
Yeah, not much I can really do about old characters.
